### ISSUE TITLE
Question q_q15, custom added question, doesn't save the answers

### ISSUE THREAD

**Issue by robertavram-md** [robertavram-md/alexa-hf#8]
**WHAT** Question q_q15, last question in the survey, asks user "Do you have angina?" Possible answers are "Yes" = 1; "No" = 0 or "I don't know" = -1. Right now the question is asked but answer is not saved in study export
Moreover, Alexa says "Survey is finished" but the "survey_completed" field == 0 where it should be 1.

**Comment by ivan-sagal** [comment]
Modifications made. Please retest.

NOTE - when adding/modifying answers and answer types in admin panel, they need to be manually pulled in the skill. When we do such changes on our end - we make skill update to test the changes. Otherwise, skill is being being automatically updated once per day. As we see you are not testing the local skill version on your end, but do the testing with the skill on our server. As a result, once you make answer / answer type change ping us to update the skill. We made skill to auto-update once per 5 minutes.

As I mentioned during one of our call that changes in admin panel are immediate - I assumes that you would update the skill version on your end manually. I believe this created some misunderstanding.
